config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :chairs, only: %i[index new create show] do
    resources :bookings, only: %i[create]
  end

  resources :bookings, only: %i[index]
  resources :owner_bookings, only: %i[index] do
    member do
      patch :accept
      patch :deny
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :chair

  validates :start_time, :end_time, presence: true
  validate :end_time_cannot_be_in_the_past

  private

  def end_time_cannot_be_in_the_past
    if end_time && start_time && end_time < start_time
      errors.add(:end_time, "can't be before start time")
    end
  end
end

app/models/chair.rb
class Chair < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :name, :price_per_day, presence: true
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chairs, dependent: :destroy
  has_many :owner_bookings, through: :chairs, source: :bookings # PROPRIETAIRE

  has_many :bookings # LOCATAIRE*

  validates :first_name, :last_name, presence: true
  validates :photo, presence: true

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:index]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_chair, only: %i[create]

  def index
    @bookings = current_user.bookings
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.status = "pending"
    @booking.user = current_user
    @booking.chair = @chair

    if @booking.valid?
      @booking.total_price = @chair.price_per_day * (@booking.end_time - @booking.start_time).to_i

      @booking.save
      redirect_to bookings_path, notice: "You have booked this chair! Waiting for owner's approval..." # renvoi vers les résas du locataire
    else
      render "chairs/show", status: :unprocessable_entity
    end
  end

  private

  def set_chair
    @chair = Chair.find(params[:chair_id])
  end

  def booking_params
    params.require(:booking).permit(:start_time, :end_time)
  end
end

app/controllers/chairs_controller.rb
class ChairsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @chairs = Chair.all
    @markers = @chairs.geocoded.map do |chair|
      {
        lat: chair.latitude,
        lng: chair.longitude,
        info_window: render_to_string(partial: "info_window", locals: {chair: chair}),
        image_url: helpers.asset_url("map-pin-solid.svg")
      }
    end
  end

  def show
    @chair = Chair.find(params[:id])
    @booking = Booking.new
  end

  def new
    @chair = Chair.new
  end

  def create
    @chair = Chair.new(chair_params)
    @chair.rating = 0
    @chair.user = current_user
    @chair.save
    redirect_to chair_path(@chair)
  end

  private

  def chair_params
    params.require(:chair).permit(:name, :description, :address, :price_per_day, :photo)
  end
end

app/controllers/owner_bookings_controller.rb
class OwnerBookingsController < ApplicationController
  def index
    @bookings = current_user.owner_bookings.order(created_at: :desc)
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "validated"
    @booking.save

    redirect_to owner_bookings_path(current_user)
  end

  def deny
    @booking = Booking.find(params[:id])
    @booking.status = "denied"
    @booking.save

    redirect_to owner_bookings_path(current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container_reservation">
  <h2 class="titre-reservation">Mes réservations :</h2>

  <% @bookings.each do |booking| %>
    <div class="card-reservation">
      <div class="p-0 h-100">
        <%= cl_image_tag booking.chair.photo.key, crop: :fill, width: 300 %>
      </div>
      <div class="card-reservation-infos">
        <div>
          <h2><%= booking.chair.name.capitalize %></h2>
          <div class="date-reservation">
            <p><i class="fa-solid fa-calendar-days p-1"></i>  Date de réservation : <%= booking.start_time.strftime("%d/%m/%Y") %> - <%= booking.end_time.strftime("%d/%m/%Y") %></p>
            <p class="price"><%= booking.total_price %> €</p>
          </div>
        </div>
        <div class="price_status">
          <% case booking.status %>
          <% when "pending" %>
           <p><div class="pending">En attente </div></p>
          <% when "validated" %>
            <p><div class="validated">Accepté<div></p>
          <% when "denied" %>
            <p> <div class="denied">Refusé</div></p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/chairs/_info_window.html.erb
<h2><%= chair.name %></h2>
<p><%= chair.address %></p>

app/views/chairs/index.html.erb
<div class="index-title" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1554752191-b9e763720f91?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2946&q=80);">
  <div class="container">
    <h1 style="color: white;">Les chaises disponibles</h1>
    <p style="color: white; text-align: center">Chaise longue, Rockingchair, chaise de camping... Louez votre chaise de rêve près de chez vous !</p>
  </div>
</div>

<div class="flexbox px-4">
  <div class="cards col-6 mr-2">
    <% @chairs.each do |chair| %>
      <%= link_to chair_path(chair), class: "card-index-link" do %>
        <div class="card-index">
          <%= cl_image_tag(chair.photo.key) %>
          <div class="card-index-infos px-2 mt-2 ms-2">
            <div class="style-card">
              <h2><%= chair.name.upcase %></h2>
              <% chair.rating.floor.times do %>
                <i class="fa-solid fa-star text-yellow"></i>
              <% end %>
              <% if chair.rating < 5 %>
              <% if (chair.rating * 2.0).round / 2.0 - chair.rating.floor == 0%>
                <i class="fa-regular fa-star text-yellow"></i>
              <% else %>
                <i class="fa-solid fa-star-half-stroke text-yellow"></i>
                <% end %>
                <% (5 - chair.rating.floor - 1).times do %>
                <i class="fa-regular fa-star text-yellow"></i>
                <% end %>
                <% end %>
              <p><%= chair.description.truncate(100) %></p>
            </div>
            <h2 class="card-index-pricing"><%= chair.price_per_day %> € / jour</h2>
            <%= cl_image_tag(chair.user.photo.key,  width: 40, height: 40, crop: :fill, class:"card-index-user avatar-bordered") %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="map col-6 ml-2">
    <div style="width: calc(100% - 24px); height: calc(100vh - 48px); border-radius: 5px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/chairs/new.html.erb
<div class="chair" >
  <div class="left">
    <h1>Ma nouvelle chaise</h1>
    <%= simple_form_for [@chair] do |f| %>
      <%= f.input :name, label: "Nom de ma chaise" %>
      <%= f.input :description %>
      <%= f.input :address, label: "Adresse" %>
      <%= f.input :price_per_day, label: "Prix par jour" %>
      <%= f.input :photo, as: :file, label: "Photo de ma chaise" %>
      <%= f.submit "J'ajoute ma chaise", class: "btn btn-chair" %>
    <% end %>
  </div>

  <div class=right>
    <%= image_tag "fauteuil_blanc.jpg", width: "100%" %>
  </div>
</div>

app/views/chairs/show.html.erb
<div class="flex-container px-5">
  <div >
    <div class="d-flex flex-1 align-items-center justify-content-around">
      <div class="w-50">
        <h2>Chaise <%= @chair.name %></h2>
        <p class="card-address">
          <i class="fa-solid fa-star" style="margin-right: 4px;"></i><%= @chair.rating %>
          <i class="fa-solid fa-location-pin" style="margin-left: 20px; margin-right: 4px;"></i>   <%= @chair.address %>
        </p>

        <%# <div class="chair-400-600">
          <%= cl_image_tag @chair.photo.key %>
        <%# </div> %>

        <div class="card-trip">
          <%= cl_image_tag @chair.photo.key, width: 1200, crop: :scale %>
          <div class="card-trip-infos">
            <div>
              <h2><%= @chair.name.upcase %></h2>
              <p><%= @chair.description %></p>
            </div>
            <h2 class="card-trip-pricing"><span id="price_per_day"><%=@chair.price_per_day%></span> € / jour</h2>
            <%= cl_image_tag @chair.user.photo.key, width: 400, crop: :thumb, class: "card-trip-user avatar-bordered" %>
          </div>
        </div>
      </div>

      <div class="form">
        <div data-controller="display-price" data-display-price-chair-price-value="<%=@chair.price_per_day%>" class="rounded border p-2 border-bottom">
          <h2 class="text-center"><%="Réservez votre chaise !"%></h2>
          <hr />
            <%= simple_form_for([@chair, @booking]) do |f| %>
              <%= f.input :start_time, as: :date, html5: true, label: "Début de réservation", input_html: {min: Date.today, data: {action: "change->display-price#compute", display_price_target: "startDate"}}%>
              <%= f.input :end_time, as: :date, html5: true, label: "Fin de réservation", input_html: {min: Date.today, data: {action: "change->display-price#compute", display_price_target: "endDate"}}%>
              <p class="d-none" data-display-price-target="priceContainer">PRIX TOTAL: <span data-display-price-target="totalPrice">0 €</span></p>
              <div class="d-flex justify-content-center">
                <%= f.button :submit, "Réserver", disabled: true, class: "btn btn-chair", data: { display_price_target: "button" }%>
              </div>
            <% end %>
        </div>

      </div>

    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chairbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice m-0"><%= notice %></p>
    <p class="alert m-0"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/owner_bookings/index.html.erb
<div class="container_reservation">
  <h2 class="titre-reservation">Regarde tout ce que tu as déjà loué !</h2>

  <% @bookings.each do |booking| %>
    <div class="card-reservation">
      <div class="p-0 h-100">
        <%= cl_image_tag booking.chair.photo.key, crop: :fill, width: 300 %>
      </div>
      <div class="card-reservation-infos">
        <div>
          <h2><%= booking.chair.name.capitalize %></h2>
          <div class="date-reservation">
            <p><i class="fa-solid fa-calendar-days p-1"></i>  Date de réservation : <%= booking.start_time.strftime("%d/%m/%Y") %> - <%= booking.end_time.strftime("%d/%m/%Y") %></p>
            <p class="price"><%= booking.total_price %> €</p>
          </div>
        </div>
        <div class="price_status">
          <% case booking.status %>
          <% when "pending" %>
            <p><div class="pending">En attente </div></p>
          <% when "validated" %>
            <p><div class="validated">Accepté</div></p>
          <% when "denied" %>
            <p><div class="denied">Refusé</div></p>
          <% end %>
          <% if booking.status == "pending" %>
            <div class="d-flex justify-content-around">
              <%= link_to "J'accepte", accept_owner_booking_path(booking), data: {turbo_method: :patch}, class:"button_accept" %></div>
              <%= link_to "Je refuse", deny_owner_booking_path(booking), data: {turbo_method: :patch}, class:"button_refused" %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner home" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1570034821021-cd00a221e608?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2940&q=80);">
  <div class="container">
    <h1 class="title home">🪑 Bienvenue sur Chairbnb 🪑</h1>
    <p class="subtitle home">Les plus belles chaises pour les plus belles fesses.</p>
    <%= link_to "Trouvez votre chaise", chairs_path, class: "btn-home" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "red-chair.png" %>
       <div class="chairbnb">ChairBnB.com</div>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Toutes les chaises", chairs_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Ajouter une chaise", new_chair_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, crop: :thumb, height: 40, width: 40, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mes réservations", bookings_path, class: "dropdown-item" %>
              <%= link_to "Mes chaises en location", owner_bookings_path, class: "dropdown-item" %>
              <%= link_to "Déconnexion", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>